# UltraCapes Configuration-File VER2:

# Here you can set the Message which will be sent to a player without permissions.

no-permissions: §cYou don't have Permissions for this action!

# Here you can set the Message which will be sent to the player after a skin reset.

skin-resetted: §aYour Skin has been resetted!

# Here you can set the UI's Title.

UI-Title: §bUltraCapes Menu

#Here you can set the Message under the UI's Title.

UI-Content: §f§l>> §r§fHere you can choose a Cape!
